In [34]:
from class_mesh_simplify import mesh_simplify
import numpy as np

In [118]:
input_filepath = 'torus.obj'
output_filepath = 'torus7.obj'
threshold = 0.01
simplify_ratio = 0.1

In [119]:
model = mesh_simplify(input_filepath, threshold, simplify_ratio)

Import model: torus.obj


In [120]:
model.generate_valid_pairs()

In [121]:
model.valid_pairs.shape

(2400, 2)

In [123]:
model.valid_pairs[:20, :]

array([[  1,   2],
       [  1,  22],
       [  1, 581],
       [  1, 600],
       [  2,   3],
       [  2,  23],
       [  2, 581],
       [  2, 582],
       [  3,   4],
       [  3,  24],
       [  3, 582],
       [  3, 583],
       [  4,   5],
       [  4,  25],
       [  4, 583],
       [  4, 584],
       [  5,   6],
       [  5,  26],
       [  5, 584],
       [  5, 585]])

In [82]:
model.valid_pairs[model.valid_pairs[:, 0] == 1]

array([[1, 2],
       [1, 3]])

In [83]:
model.valid_pairs[model.valid_pairs[:, 1] == 1]

array([[2, 1],
       [3, 1],
       [4, 1],
       [8, 1]])

In [84]:
model.points.max()

57.9273

In [102]:
dist_pairs = []

for i in range(0, model.number_of_points):
    current_point_location = i + 1
    current_point = model.points[i, :]
    current_point_to_others_dist = (np.sum((model.points - current_point) ** 2, axis=1)) ** 0.5
    valid_pairs_location = np.where(current_point_to_others_dist <= model.t)[0] + 1
    valid_pairs_location = valid_pairs_location.reshape(len(valid_pairs_location), 1)
    current_valid_pairs = np.concatenate([current_point_location * np.ones((valid_pairs_location.shape[0], 1)), valid_pairs_location], axis=1)
    
    if i == 0:
        dist_pairs = current_valid_pairs
    else:
        dist_pairs = np.concatenate([dist_pairs, current_valid_pairs], axis=0)

In [86]:
dist_pairs.shape

(2138, 2)

In [87]:
dist_pairs = np.array(dist_pairs)
find_same = dist_pairs[:, 1] - dist_pairs[:, 0]
find_same_loc = np.where(find_same == 0)[0]
dist_pairs = np.delete(dist_pairs, find_same_loc, axis=0)

In [88]:
dist_pairs.shape

(136, 2)

In [89]:
if dist_pairs.size > 0:
    valid_pairs = np.concatenate([model.edges, dist_pairs], axis=0)
    valid_pairs = np.array(valid_pairs, dtype=int)
else:
    valid_pairs = edges

In [90]:
valid_pairs.shape

(9858, 2)

In [91]:
model.edges.shape

(9722, 2)

In [92]:
find_same = valid_pairs[:, 1] - valid_pairs[:, 0]
find_same_loc = np.where(find_same == 0)[0]
valid_pairs = np.delete(valid_pairs, find_same_loc, axis=0)

unique_valid_pairs_trans, unique_valid_pairs_loc = np.unique(valid_pairs[:, 0] * (10 ** 10) + valid_pairs[:, 1], return_index=True)
valid_pairs = valid_pairs[unique_valid_pairs_loc, :]

In [93]:
valid_pairs.shape

(9761, 2)

In [103]:
model.calculate_optimal_contraction_pairs_and_cost()

In [104]:
model.iteratively_remove_least_cost_valid_pairs()

Simplification: 100.0%
Remaining: 600 points


Simplification: 83.33333333333333%
Remaining: 500 points


Simplification: 66.66666666666667%
Remaining: 400 points


Simplification: 50.0%
Remaining: 300 points


Simplification: 33.333333333333336%
Remaining: 200 points


Simplification: 16.666666666666668%
Remaining: 100 points


Simplification: 5.170902716914987%
Remaining: 59 points
End



In [105]:
model.generate_new_3d_model()

In [106]:
model.output(output_filepath)

Output simplified model: torus7.obj


In [109]:
model.valid_pairs.shape

(1626, 2)